max_linear_velocity: 0.4
max_linear_acceleration: 0.8
max_angular_velocity: 0.5
max_angular_acceleration: 1.0
linear_goal_tolerance: 0.2
angular_goal_tolerance: 0.1 
control_frame: world
end_effector_frame: base_link
goal_wait_time: 5